"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { api, Project, Runner, short, when } from "../lib/api";
import { useSession } from "../components/session";
import { useData } from "../components/data";
import { Dialog, Empty, Notice } from "../components/ui";
import { Icon } from "../components/icons";

export default function ProjectsPage() {
  const { token } = useSession();
  const { data: [rawProjects, rawRunners], error, loading, refresh, updated } = useData<[Project[] | null, Runner[] | null]>(["/projects", "/runners"], [[], []]);
  const projects = rawProjects ?? []; const runners = rawRunners ?? [];
  const [query, setQuery] = useState(""); const [create, setCreate] = useState(false); const [busy, setBusy] = useState(false); const [formError, setFormError] = useState(""); const [notice, setNotice] = useState("");
  const online = runners.filter(r => r.online);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setFormError("");
    try { const project = await api<Project>(token, "/projects", { method: "POST", body: JSON.stringify({ name: String(form.get("name")).trim(), repo: String(form.get("repo")).trim(), branch: String(form.get("branch")).trim() || "main" }) }); setCreate(false); setNotice(`${project.name} is ready. Open the project to create your first task.`); refresh(); }
    catch (e) { setFormError(e instanceof Error ? e.message : "Project could not be created."); }
    finally { setBusy(false); }
  }
  const filtered = projects.filter(p => `${p.name} ${p.repo_path}`.toLowerCase().includes(query.toLowerCase()));
  return <main id="main" className="page"><div className="page-heading"><div><span className="eyebrow">YOUR CONTROL PLANE</span><h1>Projects</h1><p>Keep the work moving. Keep the main branch steady.</p></div><button className="button primary" onClick={() => { setCreate(true); setFormError(""); }}><Icon name="plus"/>New project</button></div>
    {error && <Notice danger>{error} {updated && "Showing the last successful snapshot."} <button className="text-button" onClick={refresh}>Retry</button></Notice>}{notice && <Notice>{notice}</Notice>}
    <div className="stats-grid"><div className="stat"><span><Icon name="grid"/>Connected projects</span><strong>{loading ? "—" : projects.length}</strong><small>Repositories in your workspace</small></div><div className="stat"><span><Icon name="server"/>Available runners</span><strong>{loading ? "—" : online.length}<i> / {runners.length}</i></strong><small>{online.length ? "Ready to take on new work" : "Start a runner to execute tasks"}</small></div><div className="stat callout"><span><Icon name="shield"/>A clear path to main</span><p>Assign in isolation.<br/>Review with context.<br/><strong>Integrate with confidence.</strong></p></div></div>
    <div className="content-columns"><section><div className="section-header"><h2>Your repositories <span className="count">{projects.length}</span></h2><button className="icon-button" onClick={refresh} aria-label="Refresh projects"><Icon name="refresh"/></button></div><div className="search"><Icon name="search"/><input aria-label="Search projects" placeholder="Find a project or repository…" value={query} onChange={e => setQuery(e.target.value)}/><kbd>/</kbd></div>
    {loading ? <div className="skeleton" role="status">Loading projects…</div> : filtered.length ? <div className="project-list">{filtered.map((project, i) => <Link className="project-card" href={`/projects/${project.id}`} key={project.id}><div className={`project-avatar color-${i % 4}`}>{project.name.slice(0, 2).toUpperCase()}</div><div className="project-summary"><h3>{project.name}</h3><p className="mono">{project.repo_path}</p><div className="project-meta"><span><Icon name="branch"/>{project.branch}</span><span>{short(project.canonical_sha)}</span></div></div><Icon name="arrow" className="project-arrow"/></Link>)}</div> : <div className="panel"><Empty title={query ? "No matching projects" : "Your next project starts here"}>{query ? "Try a different name or repository path." : "Connect a local Git repository with an existing commit. Your code stays where it is."}</Empty>{!query && <div className="empty-action"><button className="button secondary" onClick={() => setCreate(true)}><Icon name="plus"/>Connect a repository</button></div>}</div>}
    <p className="refresh-note"><span className={`connection-dot ${error ? "" : "connected"}`}/>{error ? "Refresh paused by connection error" : "Refreshes every 5 seconds"}{updated && ` · Last checked ${updated.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`}</p></section>
    <aside className="right-column"><section className="panel runners-panel"><div className="section-header"><h2>Runner fleet</h2><Icon name="server"/></div>{runners.length ? <div className="runner-list">{runners.map(r => <div className="runner" key={r.id}><span className={`connection-dot ${r.online ? "connected" : ""}`}/><div><strong>{r.hostname}</strong><p>{r.os} / {r.arch}</p><small>{r.online ? (r.capabilities ?? []).join(" · ") || "Connected" : `Last seen ${when(r.last_seen)}`}</small></div><span className={`badge ${r.online ? "status-ready" : ""}`}>{r.online ? "online" : "offline"}</span></div>)}</div> : <div className="runner-empty"><Icon name="server"/><h3>No runners connected</h3><p>Start a local runner to execute tasks in isolated workspaces.</p><Link className="text-link" href="/guide#runners">Runner setup <Icon name="arrow"/></Link></div>}</section><section className="guide-card"><span className="eyebrow">FROM INTENT TO INTEGRATION</span><h3>A workspace for every idea.</h3><p>Tasks become isolated worktrees. Completed work becomes a changeset. You decide what reaches the canonical branch.</p><Link href="/guide" className="text-link">Explore the workflow <Icon name="arrow"/></Link></section></aside></div>
    {create && <Dialog title="Connect a project" onClose={() => !busy && setCreate(false)}><form onSubmit={submit}><p className="form-intro">Use an existing local Git repository with a clean canonical branch and at least one commit.</p><label htmlFor="project-name">Project name</label><input id="project-name" name="name" placeholder="Platform engineering" required maxLength={160} autoFocus/><label htmlFor="repo-path">Repository path</label><input id="repo-path" name="repo" placeholder="/home/you/projects/platform" required/><p className="field-help">Absolute path on the machine running the Ballast server.</p><label htmlFor="branch">Canonical branch</label><input id="branch" name="branch" defaultValue="main" required/>{formError && <Notice danger>{formError}</Notice>}<div className="dialog-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setCreate(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy ? "Connecting…" : "Connect project"}<Icon name="arrow"/></button></div></form></Dialog>}
  </main>;
}
